
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: backend
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
