
services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads

